version: '3.8'
services:
  frontend:
    build: 
      context: ./credence-frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=https://credence-backend-docker.azurewebsites.net
    ports:
      - 3000:80
    
  backend:
    build: 
      context: ./expenseTracker
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://credence-db.postgres.database.azure.com:5432/expenseTracker
      - DB_username=postgres
      - DB_password=Credence@123
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=expenseTracker
    volumes:
      - credence-data:/var/lib/postgresql/data

volumes:
  # default location \var\lib\docker\volumes
  credence-data: