version: '3.8'
services:
  frontend:
    build: 
      context: ./credence-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    
  backend:
    build: 
      context: ./expenseTracker
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=expenseTracker
    volumes:
      - credence-data:/var/lib/postgresql/data

volumes:
  # default location \var\lib\docker\volumes
  credence-data: